<?php


namespace Cradle\Http;

use PHPUnit_Framework_TestCase;
use Cradle\Http\Request;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-29 at 06:57:17.
 */
class Cradle_Http_Router_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var Router
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Router;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Cradle\Http\Router::match
     */
    public function testMatch()
    {
		$results = $this->object->match('get', '/foobar');
		$this->assertEmpty($results);
    }

    /**
     * @covers Cradle\Http\Router::process
     */
    public function testProcess()
    {
		$request = new Request();
		$this->assertTrue($this->object->process($request));
    }

    /**
     * @covers Cradle\Http\Router::route
     */
    public function testRoute()
    {
		$instance = $this->object->route('foobar', '/foo/bar', function() {});
		$this->assertInstanceOf('Cradle\Http\Router', $instance);
    }
}
