<?php 

namespace Cradle\Sql\Sqlite;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:03.
 */
class Cradle_Sql_Sqlite_QueryUtility_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var QueryUtility
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new QueryUtility;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Cradle\Sql\Sqlite\QueryUtility::dropTable
     */
    public function testDropTable()
    {
        $instance = $this->object->dropTable('foobar');
		$this->assertInstanceOf('Cradle\Sql\Sqlite\QueryUtility', $instance);
    }

    /**
     * @covers Cradle\Sql\Sqlite\QueryUtility::getQuery
     */
    public function testGetQuery()
    {
        $actual = $this->object->getQuery();
		$this->assertEquals(';', $actual);
    }

    /**
     * @covers Cradle\Sql\Sqlite\QueryUtility::renameTable
     */
    public function testRenameTable()
    {
        $instance = $this->object->renameTable('foo', 'bar');
		$this->assertInstanceOf('Cradle\Sql\Sqlite\QueryUtility', $instance);
    }

    /**
     * @covers Cradle\Sql\Sqlite\QueryUtility::showColumns
     */
    public function testShowColumns()
    {
        $instance = $this->object->showColumns('foobar');
		$this->assertInstanceOf('Cradle\Sql\Sqlite\QueryUtility', $instance);
    }

    /**
     * @covers Cradle\Sql\Sqlite\QueryUtility::showTables
     */
    public function testShowTables()
    {
        $instance = $this->object->showTables();
		$this->assertInstanceOf('Cradle\Sql\Sqlite\QueryUtility', $instance);
    }

    /**
     * @covers Cradle\Sql\Sqlite\QueryUtility::truncate
     */
    public function testTruncate()
    {
        $instance = $this->object->truncate('foobar');
		$this->assertInstanceOf('Cradle\Sql\Sqlite\QueryUtility', $instance);
    }
}
