<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:00.
 */
class Cradle_Handlebars_HandlebarsRuntime_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var HandlebarsRuntime
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HandlebarsRuntime;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Cradle\Handlebars\HandlebarsRuntime::flush
     * @todo   Implement testFlush().
     */
    public function testFlush()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Handlebars\HandlebarsRuntime::getHelper
     * @todo   Implement testGetHelper().
     */
    public function testGetHelper()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Handlebars\HandlebarsRuntime::getHelpers
     * @todo   Implement testGetHelpers().
     */
    public function testGetHelpers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Handlebars\HandlebarsRuntime::getPartial
     * @todo   Implement testGetPartial().
     */
    public function testGetPartial()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Handlebars\HandlebarsRuntime::getPartials
     * @todo   Implement testGetPartials().
     */
    public function testGetPartials()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Handlebars\HandlebarsRuntime::registerHelper
     * @todo   Implement testRegisterHelper().
     */
    public function testRegisterHelper()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Handlebars\HandlebarsRuntime::registerPartial
     * @todo   Implement testRegisterPartial().
     */
    public function testRegisterPartial()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Handlebars\HandlebarsRuntime::unregisterHelper
     * @todo   Implement testUnregisterHelper().
     */
    public function testUnregisterHelper()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Handlebars\HandlebarsRuntime::unregisterPartial
     * @todo   Implement testUnregisterPartial().
     */
    public function testUnregisterPartial()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
