<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:00.
 */
class Cradle_Handlebars_HandlebarsCompiler_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var HandlebarsCompiler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HandlebarsCompiler;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Cradle\Handlebars\HandlebarsCompiler::getSource
     * @todo   Implement testGetSource().
     */
    public function testGetSource()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Handlebars\HandlebarsCompiler::compile
     * @todo   Implement testCompile().
     */
    public function testCompile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Handlebars\HandlebarsCompiler::setOffset
     * @todo   Implement testSetOffset().
     */
    public function testSetOffset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Handlebars\HandlebarsCompiler::__callResolver
     * @todo   Implement test__callResolver().
     */
    public function test__callResolver()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Handlebars\HandlebarsCompiler::addResolver
     * @todo   Implement testAddResolver().
     */
    public function testAddResolver()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Handlebars\HandlebarsCompiler::getResolverHandler
     * @todo   Implement testGetResolverHandler().
     */
    public function testGetResolverHandler()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Handlebars\HandlebarsCompiler::resolve
     * @todo   Implement testResolve().
     */
    public function testResolve()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Handlebars\HandlebarsCompiler::resolveShared
     * @todo   Implement testResolveShared().
     */
    public function testResolveShared()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Handlebars\HandlebarsCompiler::resolveStatic
     * @todo   Implement testResolveStatic().
     */
    public function testResolveStatic()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Handlebars\HandlebarsCompiler::setResolverHandler
     * @todo   Implement testSetResolverHandler().
     */
    public function testSetResolverHandler()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Handlebars\HandlebarsCompiler::bindCallback
     * @todo   Implement testBindCallback().
     */
    public function testBindCallback()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
