<?php

namespace Cradle\Image;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:01.
 */
class Cradle_Image_ImageException_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var ImageException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ImageException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Cradle\Image\ImageException::forGDNotInstalled
     * @todo   Implement testForGDNotInstalled().
     */
    public function testForGDNotInstalled()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Image\ImageException::forInvalidImageFile
     * @todo   Implement testForInvalidImageFile().
     */
    public function testForInvalidImageFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
