<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:02.
 */
class Cradle_Resolver_ResolverException_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var ResolverException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ResolverException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Cradle\Resolver\ResolverException::forInvalidCallback
     * @todo   Implement testForInvalidCallback().
     */
    public function testForInvalidCallback()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Resolver\ResolverException::forClassNotFound
     * @todo   Implement testForClassNotFound().
     */
    public function testForClassNotFound()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Resolver\ResolverException::forMethodNotFound
     * @todo   Implement testForMethodNotFound().
     */
    public function testForMethodNotFound()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Resolver\ResolverException::forResolverNotFound
     * @todo   Implement testForResolverNotFound().
     */
    public function testForResolverNotFound()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
