<?php 

namespace Cradle\Sql;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:02.
 */
class Cradle_Sql_AbstractSql_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var AbstractSql
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AbstractSql;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Cradle\Sql\AbstractSql::bind
     * @todo   Implement testBind().
     */
    public function testBind()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::collection
     * @todo   Implement testCollection().
     */
    public function testCollection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::deleteRows
     * @todo   Implement testDeleteRows().
     */
    public function testDeleteRows()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::getBinds
     * @todo   Implement testGetBinds().
     */
    public function testGetBinds()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::getConnection
     * @todo   Implement testGetConnection().
     */
    public function testGetConnection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::getDeleteQuery
     * @todo   Implement testGetDeleteQuery().
     */
    public function testGetDeleteQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::getInsertQuery
     * @todo   Implement testGetInsertQuery().
     */
    public function testGetInsertQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::getLastInsertedId
     * @todo   Implement testGetLastInsertedId().
     */
    public function testGetLastInsertedId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::getModel
     * @todo   Implement testGetModel().
     */
    public function testGetModel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::getRow
     * @todo   Implement testGetRow().
     */
    public function testGetRow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::getSelectQuery
     * @todo   Implement testGetSelectQuery().
     */
    public function testGetSelectQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::getUpdateQuery
     * @todo   Implement testGetUpdateQuery().
     */
    public function testGetUpdateQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::insertRow
     * @todo   Implement testInsertRow().
     */
    public function testInsertRow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::insertRows
     * @todo   Implement testInsertRows().
     */
    public function testInsertRows()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::model
     * @todo   Implement testModel().
     */
    public function testModel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::query
     * @todo   Implement testQuery().
     */
    public function testQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::search
     * @todo   Implement testSearch().
     */
    public function testSearch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::setBinds
     * @todo   Implement testSetBinds().
     */
    public function testSetBinds()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::setRow
     * @todo   Implement testSetRow().
     */
    public function testSetRow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::updateRows
     * @todo   Implement testUpdateRows().
     */
    public function testUpdateRows()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::getEventHandler
     * @todo   Implement testGetEventHandler().
     */
    public function testGetEventHandler()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::on
     * @todo   Implement testOn().
     */
    public function testOn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::setEventHandler
     * @todo   Implement testSetEventHandler().
     */
    public function testSetEventHandler()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::trigger
     * @todo   Implement testTrigger().
     */
    public function testTrigger()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::i
     * @todo   Implement testI().
     */
    public function testI()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::loop
     * @todo   Implement testLoop().
     */
    public function testLoop()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::when
     * @todo   Implement testWhen().
     */
    public function testWhen()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::getCaller
     * @todo   Implement testGetCaller().
     */
    public function testGetCaller()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::getCallee
     * @todo   Implement testGetCallee().
     */
    public function testGetCallee()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::getInspectorHandler
     * @todo   Implement testGetInspectorHandler().
     */
    public function testGetInspectorHandler()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::inspect
     * @todo   Implement testInspect().
     */
    public function testInspect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::setInspectorHandler
     * @todo   Implement testSetInspectorHandler().
     */
    public function testSetInspectorHandler()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::addLogger
     * @todo   Implement testAddLogger().
     */
    public function testAddLogger()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::log
     * @todo   Implement testLog().
     */
    public function testLog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::loadState
     * @todo   Implement testLoadState().
     */
    public function testLoadState()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::saveState
     * @todo   Implement testSaveState().
     */
    public function testSaveState()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::__call
     * @todo   Implement test__call().
     */
    public function test__call()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::__callResolver
     * @todo   Implement test__callResolver().
     */
    public function test__callResolver()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::addResolver
     * @todo   Implement testAddResolver().
     */
    public function testAddResolver()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::getResolverHandler
     * @todo   Implement testGetResolverHandler().
     */
    public function testGetResolverHandler()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::resolve
     * @todo   Implement testResolve().
     */
    public function testResolve()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::resolveShared
     * @todo   Implement testResolveShared().
     */
    public function testResolveShared()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::resolveStatic
     * @todo   Implement testResolveStatic().
     */
    public function testResolveStatic()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\AbstractSql::setResolverHandler
     * @todo   Implement testSetResolverHandler().
     */
    public function testSetResolverHandler()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
