<?php 

namespace Cradle\Sql;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:02.
 */
class Cradle_Sql_PostGreSql_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var PostGreSql
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PostGreSql;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Cradle\Sql\PostGreSql::connect
     * @todo   Implement testConnect().
     */
    public function testConnect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\PostGreSql::getAlterQuery
     * @todo   Implement testGetAlterQuery().
     */
    public function testGetAlterQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\PostGreSql::getColumns
     * @todo   Implement testGetColumns().
     */
    public function testGetColumns()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\PostGreSql::getCreateQuery
     * @todo   Implement testGetCreateQuery().
     */
    public function testGetCreateQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\PostGreSql::getDeleteQuery
     * @todo   Implement testGetDeleteQuery().
     */
    public function testGetDeleteQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\PostGreSql::getIndexes
     * @todo   Implement testGetIndexes().
     */
    public function testGetIndexes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\PostGreSql::getInsertQuery
     * @todo   Implement testGetInsertQuery().
     */
    public function testGetInsertQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\PostGreSql::getPrimary
     * @todo   Implement testGetPrimary().
     */
    public function testGetPrimary()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\PostGreSql::getSelectQuery
     * @todo   Implement testGetSelectQuery().
     */
    public function testGetSelectQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\PostGreSql::getTables
     * @todo   Implement testGetTables().
     */
    public function testGetTables()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\PostGreSql::getUpdateQuery
     * @todo   Implement testGetUpdateQuery().
     */
    public function testGetUpdateQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\PostGreSql::setSchema
     * @todo   Implement testSetSchema().
     */
    public function testSetSchema()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Sql\PostGreSql::getUtilityQuery
     * @todo   Implement testGetUtilityQuery().
     */
    public function testGetUtilityQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
