<?php 

namespace Cradle\Sql;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:02.
 */
class Cradle_Sql_QueryInsert_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var QueryInsert
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new QueryInsert('foobar');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Cradle\Sql\QueryInsert::getQuery
     */
    public function testGetQuery()
    {
        $actual = $this->object->getQuery();
		$this->assertEquals('INSERT INTO `foobar` () VALUES ;', $actual);
    }

    /**
     * @covers Cradle\Sql\QueryInsert::set
     */
    public function testSet()
    {
        $instance = $this->object->set('foo', 'bar');
		$this->assertInstanceOf('Cradle\Sql\QueryInsert', $instance);
    }

    /**
     * @covers Cradle\Sql\QueryInsert::setTable
     */
    public function testSetTable()
    {
        $instance = $this->object->setTable('foobar');
		$this->assertInstanceOf('Cradle\Sql\QueryInsert', $instance);
    }
}
