<?php 

namespace Cradle\Sql;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:02.
 */
class Cradle_Sql_SqlFactory_Test extends PHPUnit_Framework_TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Cradle\Sql\SqlFactory::load
     */
    public function testLoad()
    {
		$mysql = SqlFactory::load(include(__DIR__.'/../assets/sql/mysql.php'));
		
		$this->assertInstanceOf('Cradle\Sql\MySql', $mysql);
		
		$pgsql = SqlFactory::load(include(__DIR__.'/../assets/sql/pgsql.php'));
		
		$this->assertInstanceOf('Cradle\Sql\PostGreSql', $pgsql);
		
		$sqlite = SqlFactory::load(include(__DIR__.'/../assets/sql/sqlite.php'));
		
		$this->assertInstanceOf('Cradle\Sql\Sqlite', $sqlite);
    }
}
