<?php

namespace Cradle\Http;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:01.
 */
class Cradle_Http_PreProcessorTrait_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var PreProcessorTrait
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PreProcessorTraitStub;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Cradle\Http\PreProcessorTrait::getPreprocessor
     * @todo   Implement testGetPreprocessor().
     */
    public function testGetPreprocessor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Http\PreProcessorTrait::preprocess
     * @todo   Implement testPreprocess().
     */
    public function testPreprocess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cradle\Http\PreProcessorTrait::setPreprocessor
     * @todo   Implement testSetPreprocessor().
     */
    public function testSetPreprocessor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}

if(!class_exists('Cradle\Http\PreProcessorTraitStub')) {
	class PreProcessorTraitStub
	{
		use PreProcessorTrait;
	}
}
